# 전적으로 spring.application.name을 참조한다.
# name 설명보면 spring.application.name를 override 한다고 되어있는데, override 하지 않는다.
# defaultContext 역시 영향일 끼치지 못한다.
aws:
    paramstore:
        enabled: true
        region: ap-northeast-2
        prefix: /config
        #        name: application # 의미없음
        profileSeparator: _
        #        defaultContext: application # 의미없음

spring:
    config:
        activate:
            on-profile: local

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: 'jdbc:mysql://localhost:19910/release_me'
        username: 'root'
        password: 'test'
        hikari:
            jdbc-url: ${spring.datasource.url}
            username: ${spring.datasource.username}
            password: ${spring.datasource.password}
            driver-class-name: ${spring.datasource.driver-class-name}
            data-source-properties:
                rewriteBatchedStatements: true
            connection-timeout: 5000
            validation-timeout: 3000
            maximum-pool-size: 30
            minimum-idle: 2
            idle-timeout: 30000
            max-lifetime: 60000

    jpa:
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                order_inserts: true
                order_updates: true
                jdbc:
                    batch_size: 2000
                dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        hibernate:
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
            ddl-auto: update
