spring:
    config:
        import: 'aws-parameterstore:'
    profiles:
        active: prod
    application:
        name: release-me

---

spring:
    config:
        import: 'aws-parameterstore:'
    profiles:
        active: local
    application:
        name: release-me
