server:
    port: 7000
    
spring:
    config:
        import: 'aws-parameterstore:'
    profiles:
        active: prod
    application:
        name: release-me

---
server:
    port: 7000

spring:
    config:
        import: 'aws-parameterstore:'
    profiles:
        active: local
    application:
        name: release-me
